TronicStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'
urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf', views.admin_order_pdf, name='admin_order_pdf'),
]

shop/urls.py
from django.urls import path
from .import views


app_name = 'shop'
urlpatterns = [
    path('contact-us/', views.contact, name='contact'),
    path('about-us/', views.about, name='about'),
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm


# Create your views here.
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
        return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'override': True})
    coupon_apply_form = CouponApplyForm()
    return render(request, 'cart/detail.html', {'cart': cart,
                                                'coupon_apply_form': coupon_apply_form,})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block content %}
<!-- Shopping Cart -->
	<div class="shopping-cart section">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<!-- Shopping Summery -->
					<table class="table shopping-summery">
						<thead>
							<tr class="main-hading">
								<th>IMAGE</th>
								<th>PRODUCT</th>
								<th class="text-center">QUANTITY</th>
								<th class="text-center">REMOVE</th>
								<th class="text-center">UNIT PRICE</th>
								<th class="text-center">TOTAL</th>
							</tr>
						</thead>
						<tbody>
                        {% for item in cart %}
                        {% with product=item.product %}
							<tr>
								<td class="image" data-title="No"><img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="#"></td>
								<td class="product-des" data-title="Description">
									<p class="product-name"><a href="#">{{ product.name }}</</a></p>
								</td>

								<form action="{% url "cart:cart_add" product.id %}" method="post">{% csrf_token %}
                                <td class="qty" data-title="Qty"><!-- Input Order -->
									{% for field in item.update_quantity_form %}
                                        {% if field.html_name.lower == 'quantity' %}
									    <div class="input-group">
									    	<div class="button minus">
									    		<button type="button" class="btn btn-primary btn-number" disabled="disabled" data-type="minus" data-field="{{field.name}}">
									    			<i class="ti-minus"></i>
									    		</button>
									    	</div>
									    	<input type="text" class="input-number" id="{{ field.id_for_label }}" name="{{ field.name }}"  data-min="1" data-max="1000" value="{{ item.quantity }}">

									    	<div class="button plus">
									    		<button type="button" class="btn btn-primary btn-number" data-type="plus" data-field="{{field.name}}">
									    			<i class="ti-plus"></i>
									    		</button>
									    	</div>
                                        {{ field.errors}}
										<div class="add-to-cart">
											<input class="btn" type="submit" value="Update"></input>
										</div>
									    </div>
                                        {% endif %}
                                    {% endfor %}
                                    {{ item.update_quantity_form.override }}
									<!--/ End Input Order -->
								</td>
                                </form>
                                <form action="{% url "cart:cart_remove" product.id %}" method="post">
                                    <td class="action" data-title="Remove"><input class="btn " type="submit" value="remove"></input></td>
								{% csrf_token %}
                                </form>
                                <td class="price" data-title="Price"><span>${{ item.price }} </span></td>
                                <td class="total-amount" data-title="Total"><span>${{item.total_price}}</span></td>
							</tr>
                        {% endwith %}
                        {% endfor %}
						</tbody>
					</table>
					<!--/ End Shopping Summery -->
				</div>
			</div>
			<div class="row">
				<div class="col-12">
					<!-- Total Amount -->
					<div class="total-amount">
						<div class="row">
							<div class="col-lg-8 col-md-5 col-12">
								<div class="left">
                                 <div class="coupon">
										<form action="{% url "coupons:apply" %}" method="post">{% csrf_token %}
                                        {% for field in coupon_apply_form %}
											<input name="{{field.name}}" id="{{field.id_for_label}}" placeholder="Enter Your Coupon">
											<button type="submit" class="btn">Apply</button>
                                        {% endfor %}
										</form>
									</div>
								</div>
							</div>
							<div class="col-lg-4 col-md-7 col-12">
								<div class="right">
									<ul>
                                    <li>Cart Subtotal<span>${{ cart.get_total_price|floatformat:2 }}</span></li>
                                    {% if cart.coupon %}
                                        <li>Coupon<span>{% with code=cart.coupon.code discount=cart.coupon.discount %}"{{ code }}"</span>
                                        <li>({{ discount }}% off)<span class="text-danger">- ${{ cart.get_discount|floatformat:2 }}</span></li>
                                            {% endwith %}
                                    {% endif %}
										<li>Shipping<span>Free</span></li>
										<li class="last">You Pay<span>${{ cart.get_total_price_after_discount|floatformat:2 }}</span></li>
									</ul>
									<div class="button5">
										<a href="{% url "orders:order_create" %}" class="btn">Checkout</a>
										<a href="{% url "shop:product_list" %}" class="btn">Continue shopping</a>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!--/ End Total Amount -->
				</div>
			</div>
		</div>
	</div>
	<!--/ End Shopping Cart -->
    

{% endblock content %}