TronicStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf', views.admin_order_pdf, name='admin_order_pdf'),
]

shop/urls.py
from django.urls import path
from .import views


app_name = 'shop'
urlpatterns = [
    path('contact-us/', views.contact, name='contact'),
    path('about-us/', views.about, name='about'),
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    
]

shop/models.py
from django.db import models
from django.urls import reverse
from parler.models import TranslatableModel, TranslatedFields


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(
    Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm


# Create your views here.
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form,})

def contact(request):
    return render(request, 'shop/contact.html')

def about(request):
    return render(request, 'shop/about.html')

shop/templates/shop/about.html
{%extends "shop/base.html"%} {%load static%} {%block title%}About-us
{%endblock%} {% block content %}
<!-- About Us -->
<section class="about-us section">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-12">
        <div class="about-content">
          <h3>Welcome To <span>TronicStore</span></h3>
          <p>
            The latest destination for Electronic Gadgets.Providing Nigerian
            with a Visual to global trends,Informing Our Readers about the best
            quality of our products at an affoedable price at TronicStore.
          </p>
          <p>
            TronicStore,Will make your shopping experience on the Tronic site
            effortless and enjoyable.
          </p>
          <div class="button">
            <a href="#" class="btn">Our Blog</a>
            <a href="{% url 'shop:contact' %}" class="btn primary">Contact Us</a>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-12">
        <div class="about-img overlay">
          <img src="{% static 'team/Electronic.jpg' %}" alt="#" />
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End About Us -->

<!-- Start Team -->
<section id="team" class="team section">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="section-title">
          <h2>Our Expert Team</h2>
          <p>
            Some of Our Lead Developers that Helped in making this website a
            good online marketing site.
          </p>
        </div>
      </div>
    </div>
    <div class="row">
      <!-- Single Team -->
      <div class="col-lg-3 col-md-6 col-12">
        <div class="single-team">
          <!-- Image -->
          <div class="image">
            <img src="{% static 'team/Aanu.jpg' %}" alt="#" />
          </div>
          <!-- End Image -->
          <div class="info-head">
            <!-- Info Box -->
            <div class="info-box">
              <h4 class="name"><a href="#">Olatoke Aanuoluwapo</a></h4>
              <span class="designation">Graphics Designer</span>
            </div>
            <!-- End Info Box -->
            <!-- Social -->
            <div class="social-links">
              <ul class="social">
                <li>
                  <a href="#"><i class="fa fa-facebook-f"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-twitter"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-behance"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-instagram"></i></a>
                </li>
              </ul>
            </div>
            <!-- End Social -->
          </div>
        </div>
      </div>
      <!-- End Single Team -->
      <div class="col-lg-3 col-md-6 col-12">
        <div class="single-team">
          <!-- Image -->
          <div class="image">
            <img src="{% static 'team/Suzane.jpg' %}" alt="#" />
          </div>
          <!-- End Image -->
          <div class="info-head">
            <!-- Info Box -->
            <div class="info-box">
              <h4 class="name"><a href="#">Abiri Suzzane</a></h4>
              <span class="designation">Backend Lead</span>
            </div>
            <!-- End Info Box -->
            <!-- Social -->
            <div class="social-links">
              <ul class="social">
                <li>
                  <a href="#"><i class="fa fa-facebook-f"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-twitter"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-behance"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-instagram"></i></a>
                </li>
              </ul>
            </div>
            <!-- End Social -->
          </div>
        </div>
      </div>
      <!-- End Single Team -->
      <div class="col-lg-3 col-md-6 col-12">
        <div class="single-team">
          <!-- Image -->
          <div class="image">
            <img src="{% static 'team/Peters.jpg' %}" alt="#" />
          </div>
          <!-- End Image -->
          <div class="info-head">
            <!-- Info Box -->
            <div class="info-box">
              <h4 class="name"><a href="#">Peter Babalola</a></h4>
              <span class="designation">Lead Developer</span>
            </div>
            <!-- End Info Box -->
            <!-- Social -->
            <div class="social-links">
              <ul class="social">
                <li>
                  <a href="#"><i class="fa fa-facebook-f"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-twitter"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-behance"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-instagram"></i></a>
                </li>
              </ul>
            </div>
            <!-- End Social -->
          </div>
        </div>
      </div>
      <!-- End Single Team -->
      <div class="col-lg-3 col-md-6 col-12">
        <div class="single-team">
          <!-- Image -->
          <div class="image">
            <img src="{% static 'team/Tife.jpeg' %}" alt="#" />
          </div>
          <!-- End Image -->
          <div class="info-head">
            <!-- Info Box -->
            <div class="info-box">
              <h4 class="name"><a href="#">Oyewole Boluwatife</a></h4>
              <span class="designation">Front End Lead</span>
            </div>
            <!-- End Info Box -->
            <!-- Social -->
            <div class="social-links">
              <ul class="social">
                <li>
                  <a href="#"><i class="fa fa-facebook-f"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-twitter"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-behance"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-instagram"></i></a>
                </li>
              </ul>
            </div>
            <!-- End Social -->
          </div>
        </div>
      </div>
      <!-- End Single Team -->
    </div>
  </div>
</section>
<!--/ End Team Area -->

{% endblock %}

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<!-- Meta Tag -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name='copyright' content=''>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Title Tag  -->
    <title>{% block title %}TronicStore{% endblock %}</title>
	<!-- Favicon -->
	<link rel="icon" type="image/png" href="{% static 'img/rsz_logo.png' %}">
	<!-- Web Font -->
	<link href="https://fonts.googleapis.com/css?family=Poppins:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">
	
	<!-- StyleSheet -->
	
	<!-- Bootstrap -->
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">
	<!-- Magnific Popup -->
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.min.css' %}">
	<!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'assets/css/font-awesome.css' %}">
	<!-- Fancybox -->
	<link rel="stylesheet" href="{% static 'assets/css/jquery.fancybox.min.css' %}">
	<!-- Themify Icons -->
    <link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}">
	<!-- Nice Select CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/niceselect.css' %}">
	<!-- Animate CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">
	<!-- Flex Slider CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/flex-slider.min.css' %}">
	<!-- Owl Carousel -->
    <link rel="stylesheet" href="{% static 'assets/css/owl-carousel.css' %}">
	<!-- Slicknav -->
    <link rel="stylesheet" href="{% static 'assets/css/slicknav.min.css' %}">
	
	<!-- Eshop StyleSheet -->
	<link rel="stylesheet" href="{% static 'assets/css/reset.css' %}">
	<link rel="stylesheet" href="{% static 'assets/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">

	<!-- Color CSS -->
	<link rel="stylesheet" href="{% static 'assets/css/color/color1.css' %}">

	<!-- Braintree CSS -->
	<link rel="stylesheet" href="{% static 'css/braintree.css' %}">

	<link rel="stylesheet" href="#" id="colors">

	<link rel="stylesheet" href="https://s.pageclip.co/v1/pageclip.css" media="screen">

	
	
</head>
<body class="js">
	
	<!-- Preloader -->
	<div class="preloader">
		<div class="preloader-inner">
			<div class="preloader-icon">
				<span></span>
				<span></span>
			</div>
		</div>
	</div>
	<!-- End Preloader -->
	 
	<!-- Header -->
	<header class="header shop">
		<div class="middle-inner">
			<div class="container">
				<div class="row">
					<div class="col-lg-2 col-md-2 col-12">
						<!-- Logo -->
						<div class="logo">
							<a href="/"><h2>TronicStore</h2></a>
						</div>
						<!--/ End Logo -->
						<!-- Search Form -->
						<div class="search-top">
							<div class="top-search"><a href="#0"><i class="ti-search"></i></a></div>
							<!-- Search Form -->
							<div class="search-top">
								<form class="search-form">
									<input type="text" placeholder="Search here..." name="search">
									<button value="search" type="submit"><i class="ti-search"></i></button>
								</form>
							</div>
							<!--/ End Search Form -->
						</div>
						<!--/ End Search Form -->
						<div class="mobile-nav"></div>
					</div>
					<div class="col-lg-8 col-md-7 col-12">
						<div class="search-bar-top">
							<div class="search-bar">
								<form>
									<input name="search" placeholder="Search Products Here....." type="search">
									<button class="btnn"><i class="ti-search"></i></button>
								</form>
							</div>
						</div>
					</div>
					<div class="col-lg-2 col-md-3 col-12">
						<div class="right-bar">
							<!-- Search Form -->
							<div class="sinlge-bar">
								<a href="#" class="single-icon"><i class="fa fa-heart-o" aria-hidden="true"></i></a>
							</div>
							<div class="sinlge-bar">
								<a href="#" class="single-icon"><i class="fa fa-user-circle-o" aria-hidden="true"></i></a>
							</div>
							<div class="sinlge-bar shopping">
							{% with total_items=cart|length %}
        					    {% if total_items > 0 %}
        					    <a href="{% url "cart:cart_detail" %}" class="single-icon" >
								<i class="ti-bag"></i> <span class="total-count">{{ total_items }}</span>
        					    </a>
        						{% else %}
								<a href="{% url "cart:cart_detail" %}" class="single-icon" >
								<i class="ti-bag"></i> <span class="total-count">0</span>
        					    </a>
        						{% endif %}
        					{% endwith %}
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Header Inner -->
		<div class="header-inner">
			<div class="container">
				<div class="cat-nav-head">
					<div class="row">
						<div class="col-lg-9 col-12">
							<div class="menu-area">
								<!-- Main Menu -->
								<nav class="navbar navbar-expand-lg">
									<div class="navbar-collapse">	
										<div class="nav-inner">	
											<ul class="nav main-menu menu navbar-nav">
													<li class="active"><a href="/">Home</a></li>
													<li><a href="#">Shop<i class="ti-angle-down"></i></a>
														<ul class="dropdown">
															<li><a href="{% url 'cart:cart_detail' %}">Cart</a></li>
															<li><a href="{% url "orders:order_create" %}">Checkout</a></li>
														</ul>
													</li>
													<li><a href="/about-us/">About Us</a></li>
													<li><a href="/contact-us/">Contact Us</a></li>
												</ul>
										</div>
									</div>
								</nav>
								<!--/ End Main Menu -->	
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--/ End Header Inner -->
	</header>
	<!--/ End Header -->
	
	
	
	{% block content %}
	
	{% endblock content %}

	
	<!-- Start Footer Area -->
	<footer class="footer">
		<!-- Footer Top -->
		<div class="footer-top section">
			<div class="container">
				<div class="row">
					<div class="col-lg-5 col-md-6 col-12">
						<!-- Single Widget -->
						<div class="single-footer about">
							<div class="logo">
								<a href="/"><img src="{% static 'img/rsz_logo.png' %} " alt="#"></a>
							</div>

						</div>
						<!-- End Single Widget -->
					</div>
					<div class="col-lg-2 col-md-6 col-12">
						<!-- Single Widget -->
						<div class="single-footer links">
							<h4>Information</h4>
							<ul>
								<li><a href="{% url 'shop:about' %}">About Us</a></li>
								<li><a href="{% url 'shop:about' %}">Contact Us</a></li>
							</ul>
						</div>
						<!-- End Single Widget -->
					</div>
					<div class="col-lg-2 col-md-6 col-12">
						<!-- Single Widget -->
						<div class="single-footer links">
							<h4>Customer Service</h4>
							<ul>
								<li><a href="#">Payment Methods</a></li>
								<li><a href="#">Money-back</a></li>
								<li><a href="#">Returns</a></li>
								<li><a href="#">Shipping</a></li>
								<li><a href="#">Privacy Policy</a></li>
							</ul>
						</div>
						<!-- End Single Widget -->
					</div>
					<div class="col-lg-3 col-md-6 col-12">
						<!-- Single Widget -->
						<div class="single-footer social">
							<h4>Get In Tuch</h4>
							<!-- Single Widget -->
							<div class="contact">
								<ul>
									<li>Group1, Faculty of science, Adeleke university</li>
									<li>Nigeria</li>
									<li>info@tronicstore.com</li>
									<li>+234 814 455 1067</li>
								</ul>
							</div>
							<!-- End Single Widget -->
							<ul>
								<li><a href="#"><i class="ti-facebook"></i></a></li>
								<li><a href="#"><i class="ti-twitter"></i></a></li>
								<li><a href="#"><i class="ti-flickr"></i></a></li>
								<li><a href="#"><i class="ti-instagram"></i></a></li>
							</ul>
						</div>
						<!-- End Single Widget -->
					</div>
				</div>
			</div>
		</div>
		<!-- End Footer Top -->
		<div class="copyright">
			<div class="container">
				<div class="inner">
					<div class="row">
						<div class="col-lg-6 col-12">
							<div class="left">
								<p>Copyright © 2020 <a href="#" target="_blank">TronicStore</a>  -  All Rights Reserved.</p>
							</div>
						</div>
						<div class="col-lg-6 col-12">
							<div class="right">
								<img src="{% static 'assets/images/payments.png' %}" alt="">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</footer>
	<!-- /End Footer Area -->
 
	<!-- Jquery -->
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery-migrate-3.0.0.js' %}"></script>
	<script src="{% static 'assets/js/jquery-ui.min.js' %}"></script>
	<!-- Popper JS -->
	<script src="{% static 'assets/js/popper.min.js' %}"></script>
	<!-- Bootstrap JS -->
	<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
	<!-- Color JS -->
	<script src="{% static 'assets/js/colors.js' %}"></script>
	<!-- Slicknav JS -->
	<script src="{% static 'assets/js/slicknav.min.js' %}"></script>
	<!-- Owl Carousel JS -->
	<script src="{% static 'assets/js/owl-carousel.js' %}"></script>
	<!-- Magnific Popup JS -->
	<script src="{% static 'assets/js/magnific-popup.js' %}"></script>
	<!-- Waypoints JS -->
	<script src="{% static 'assets/js/waypoints.min.js' %}"></script>
	<!-- Countdown JS -->
	<script src="{% static 'assets/js/finalcountdown.min.js' %}"></script>
	<!-- Nice Select JS -->
	<script src="{% static 'assets/js/nicesellect.js' %}"></script>
	<!-- Flex Slider JS -->
	<script src="{% static 'assets/js/flex-slider.js' %}"></script>
	<!-- ScrollUp JS -->
	<script src="{% static 'assets/js/scrollup.js' %}"></script>
	<!-- Onepage Nav JS -->
	<script src="{% static 'assets/js/onepage-nav.min.js' %}"></script>
	<!-- Easing JS -->
	<script src="{% static 'assets/js/easing.js' %}"></script>
	<!-- Active JS -->
	<script src="{% static 'assets/js/active.js' %}"></script>

<script src="https://s.pageclip.co/v1/pageclip.js" charset="utf-8"></script>

	<!-- includes the Braintree JS client SDK -->
    <script src="https://js.braintreegateway.com/web/3.58.0/js/client.min.js"></script>
    <script src="https://js.braintreegateway.com/web/3.58.0/js/hosted-fields.min.js"></script>

	<script>
        {% block domready %}
        {% endblock domready %}
  	</script>
	  {% comment %} <!--Start of Tawk.to Script-->
<script type="text/javascript">
	var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
	(function(){
	var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
	s1.async=true;
	s1.src='{{tawk}}';
	s1.charset='UTF-8';
	s1.setAttribute('crossorigin','*');
	s0.parentNode.insertBefore(s1,s0);
	})();
</script>
<!--End of Tawk.to Script--> {% endcomment %}
<!--Start of Tawk.to Script-->
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/60910914185beb22b309cdfe/1f4r8mubj';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->
</body>
</html>

shop/templates/shop/contact.html
{% extends "shop/base.html" %}
{%load static%}
{%block title%}Contact-us
{%endblock%}
{%block content%}
  
	<!-- Start Contact -->
	<section id="contact-us" class="contact-us section">
		<div class="container">
				<div class="contact-head">
					<div class="row">
						<div class="col-lg-8 col-12">
							<div class="form-main">
								<div class="title">
									<h4>Get in touch</h4>
									<h3>Write us a message</h3>
								</div>
								<form class="form" method="post" action="https://send.pageclip.co/JD284uZcTfxAo53BmRTYNDGMPm5UxYle" method="post">
									<div class="row">
										<div class="col-lg-6 col-12">
											<div class="form-group">
												<label>Your Name<span>*</span></label>
												<input name="name" type="text" placeholder="">
											</div>
										</div>
										<div class="col-lg-6 col-12">
											<div class="form-group">
												<label>Your Subjects<span>*</span></label>
												<input name="subject" type="text" placeholder="">
											</div>
										</div>
										<div class="col-lg-6 col-12">
											<div class="form-group">
												<label>Your Email<span>*</span></label>
												<input name="email" type="email" placeholder="">
											</div>	
										</div>
										<div class="col-lg-6 col-12">
											<div class="form-group">
												<label>Your Phone<span>*</span></label>
												<input name="company_name" type="text" placeholder="">
											</div>	
										</div>
										<div class="col-12">
											<div class="form-group message">
												<label>your message<span>*</span></label>
												<textarea name="message" placeholder=""></textarea>
											</div>
										</div>
										<div class="col-12">
											<div class="form-group button">
												<button type="submit" class="btn ">Send Message</button>
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>
						<div class="col-lg-4 col-12">
							<div class="single-head">
								<div class="single-info">
									<i class="fa fa-phone"></i>
									<h4 class="title">Call us Now:</h4>
									<ul>
										<li>+234 814 455 1067</li>
										<li>+234 905 622 8532</li>
									</ul>
								</div>
								<div class="single-info">
									<i class="fa fa-envelope-open"></i>
									<h4 class="title">Email:</h4>
									<ul>
										<li><a href="mailto:info@yourwebsite.com">info@tronics.com</a></li>
										<li><a href="mailto:info@yourwebsite.com">support@tronics.com</a></li>
									</ul>
								</div>
								<div class="single-info">
									<i class="fa fa-location-arrow"></i>
									<h4 class="title">Our Address:</h4>
									<ul>
										<li>Group1, Faculty of science, Adeleke university, Nigeria.</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
	</section>
	<!--/ End Contact -->
	{%endblock%}
	
	